name: tensor_test_task
services:
    postgres10:
        container_name: postgresql_database
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=employees
        ports:
            - 5433:5432
        image: postgres:10.22-alpine
